### PR TITLE
sudo as owner instead of superuser

### LINKED ISSUE #1: nano override: access detection broken
The nano override at https://github.com/coderobe/dotfiles/blob/master/bash_include/functions.sh#L17 is supposed to launch nano with the right uid to gain write access if the file is unwritable by the current user; It currently always launches nano as root, even when the local user has write access to the file in question.

### PR DESCRIPTION
**Pull request by raccube**
Fixes #1

### CODE REVIEW

File: bash_include/functions.sh [hunk 1]
```diff
@@ -22,9 +22,10 @@ if $(locate_package nano); then
       fi
     done
     if [ ${WRITABLE} -eq 0 ]; then
-      cdr_log "no write permission, accessing file(s) as root..."
+      local OWNER=$(stat -c '%U' $file)
+      echo "no write permission, accessing file(s) as root..."
```
Comment (coderobe) [inline bash_include/functions.sh]: this is using echo instead of cdr_log, could you fix that?

**Review by coderobe — CHANGES_REQUESTED** [review]

**Review by coderobe — APPROVED** [review]
